### PR TITLE
Added Turkish lang

### PR DESCRIPTION
**Pull request by cnpltdncsln**

### CODE REVIEW

**Comment by grishka** [comment]
Thank you!

Could you please translate the new strings I just added? Also, do English plural rules work for Turkish?

**Comment by cnpltdncsln** [comment]
I don't know. How should i edit its file?

**Comment by grishka** [comment]
[For English](https://github.com/grishka/Smithereen/blob/master/src/main/java/smithereen/lang/EnglishPluralRules.java), there are two forms:
* "1 post" is used when the quantity is 1
* "25 posts" is used else

[For Russian](https://github.com/grishka/Smithereen/blob/master/src/main/java/smithereen/lang/RussianPluralRules.java) (and Ukrainian and other related languages), there are three:
* "1 запись" is used when quantity%10 is 1
* "3 записи" is used when quantity%10 is from 2 to 4
* "7 записей" is used else, and also regardless of the above rules when the tens digit is 1 (12, 113, 5211 etc)

What are these rules for Turkish?

**Comment by cnpltdncsln** [comment]
For Turkish, it should be like this form:

"1 gönderi" is used when the quantity is 1
"25 gönderi" is used else

**Comment by grishka** [comment]
So only one form? Okay, thank you again

**Comment by cnpltdncsln** [comment]
Yes. When quantity is plural, we don’t write it with plural tag like “s”.

**Comment by grishka** [comment]
You can already check out your translation on my instance https://friends.grishka.me (also [my profile there](https://friends.grishka.me/grishka)), as long as Turkish is your system language, detected by Accept-Language header

**Comment by cnpltdncsln** [comment]
Works well. I think invitation code is required to register – can you give me a code?

**Pull request merged**
